---
# tasks file for nodejs
- apt:
    name: curl
    state: present

- shell: |
    curl -sL https://deb.nodesource.com/setup_8.x | bash -
  
- apt:
    name: nodejs
    state: latest
    update_cache: yes
